### ISSUE TITLE
Microphone Permission Request not Appearing

### ISSUE THREAD

**Issue by Cyndakwil** [Cyndakwil/class4corona#3]
This issue only occurs on some computers. When hosting or joining a class, sometimes the microphone permission box will not pop up. This is not browser-specific, but rather seems to be computer-specific. More research should be done into `mediaDevices`.
This bug does cause the system to break as the `MediaStream` object that is added to the WebRTC call will be found undefined.

**Comment by FengchiW** [comment]
I fixed it
